/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AboutContent = IDL.Record({
  'bio' : IDL.Text,
  'photoUrl' : IDL.Text,
  'qualifications' : IDL.Text,
  'experience' : IDL.Text,
});
export const Clinic = IDL.Record({
  'id' : IDL.Nat,
  'hours' : IDL.Text,
  'mapsUrl' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'isVisible' : IDL.Bool,
  'phone' : IDL.Text,
  'bookingUrl' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FooterContent = IDL.Record({
  'address' : IDL.Text,
  'contactEmail' : IDL.Text,
  'copyright' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const HeaderContent = IDL.Record({
  'subText' : IDL.Text,
  'heroText' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'iconName' : IDL.Text,
});
export const SocialLink = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'platform' : IDL.Text,
  'iconName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClinic' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addSocialLink' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteClinic' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteService' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteSocialLink' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAbout' : IDL.Func([], [IDL.Opt(AboutContent)], ['query']),
  'getAllClinics' : IDL.Func([], [IDL.Vec(Clinic)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClinics' : IDL.Func([], [IDL.Vec(Clinic)], ['query']),
  'getFooter' : IDL.Func([], [IDL.Opt(FooterContent)], ['query']),
  'getHeader' : IDL.Func([], [IDL.Opt(HeaderContent)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getSocialLinks' : IDL.Func([], [IDL.Vec(SocialLink)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAbout' : IDL.Func([AboutContent], [], []),
  'setFooter' : IDL.Func([FooterContent], [], []),
  'setHeader' : IDL.Func([HeaderContent], [], []),
  'updateClinic' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Bool],
      [],
    ),
  'updateService' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateSocialLink' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AboutContent = IDL.Record({
    'bio' : IDL.Text,
    'photoUrl' : IDL.Text,
    'qualifications' : IDL.Text,
    'experience' : IDL.Text,
  });
  const Clinic = IDL.Record({
    'id' : IDL.Nat,
    'hours' : IDL.Text,
    'mapsUrl' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'isVisible' : IDL.Bool,
    'phone' : IDL.Text,
    'bookingUrl' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FooterContent = IDL.Record({
    'address' : IDL.Text,
    'contactEmail' : IDL.Text,
    'copyright' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const HeaderContent = IDL.Record({
    'subText' : IDL.Text,
    'heroText' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'iconName' : IDL.Text,
  });
  const SocialLink = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'platform' : IDL.Text,
    'iconName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClinic' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addSocialLink' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteClinic' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteService' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteSocialLink' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAbout' : IDL.Func([], [IDL.Opt(AboutContent)], ['query']),
    'getAllClinics' : IDL.Func([], [IDL.Vec(Clinic)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClinics' : IDL.Func([], [IDL.Vec(Clinic)], ['query']),
    'getFooter' : IDL.Func([], [IDL.Opt(FooterContent)], ['query']),
    'getHeader' : IDL.Func([], [IDL.Opt(HeaderContent)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getSocialLinks' : IDL.Func([], [IDL.Vec(SocialLink)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAbout' : IDL.Func([AboutContent], [], []),
    'setFooter' : IDL.Func([FooterContent], [], []),
    'setHeader' : IDL.Func([HeaderContent], [], []),
    'updateClinic' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Bool],
        [],
      ),
    'updateService' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateSocialLink' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };