/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutContent {
  'bio' : string,
  'photoUrl' : string,
  'qualifications' : string,
  'experience' : string,
}
export interface Clinic {
  'id' : bigint,
  'hours' : string,
  'mapsUrl' : string,
  'name' : string,
  'address' : string,
  'isVisible' : boolean,
  'phone' : string,
  'bookingUrl' : string,
}
export interface FooterContent {
  'address' : string,
  'contactEmail' : string,
  'copyright' : string,
  'contactPhone' : string,
}
export interface HeaderContent {
  'subText' : string,
  'heroText' : string,
  'imageUrl' : string,
}
export interface Service {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'iconName' : string,
}
export interface SocialLink {
  'id' : bigint,
  'url' : string,
  'platform' : string,
  'iconName' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addClinic' : ActorMethod<
    [string, string, string, string, string, string, string],
    bigint
  >,
  'addService' : ActorMethod<[string, string, string, string], bigint>,
  'addSocialLink' : ActorMethod<[string, string, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteClinic' : ActorMethod<[string, bigint], boolean>,
  'deleteService' : ActorMethod<[string, bigint], boolean>,
  'deleteSocialLink' : ActorMethod<[string, bigint], boolean>,
  'getAbout' : ActorMethod<[], [] | [AboutContent]>,
  'getAllClinics' : ActorMethod<[string], Array<Clinic>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClinics' : ActorMethod<[], Array<Clinic>>,
  'getFooter' : ActorMethod<[], [] | [FooterContent]>,
  'getHeader' : ActorMethod<[], [] | [HeaderContent]>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getSocialLinks' : ActorMethod<[], Array<SocialLink>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAbout' : ActorMethod<[string, AboutContent], undefined>,
  'setFooter' : ActorMethod<[string, FooterContent], undefined>,
  'setHeader' : ActorMethod<[string, HeaderContent], undefined>,
  'updateClinic' : ActorMethod<
    [string, bigint, string, string, string, string, string, string, boolean],
    boolean
  >,
  'updateService' : ActorMethod<
    [string, bigint, string, string, string],
    boolean
  >,
  'updateSocialLink' : ActorMethod<
    [string, bigint, string, string, string],
    boolean
  >,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];